apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: on8d6o0tb-go
  janus-idp.io/tekton: on8d6o0tb-go
  backstage.io/kubernetes-id: on8d6o0tb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on8d6o0tb-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
